name: Release 📦

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: omnidotdev/synapse-api

jobs:
  docker:
    name: Build and push container 🐳
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  schema:
    name: Publish GraphQL schema 📋
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install oras
        uses: oras-project/setup-oras@v1

      - name: Log in to container registry
        run: oras login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push GraphQL schema
        run: |
          oras push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-graphql:latest \
            --artifact-type application/vnd.omni.graphql \
            src/generated/graphql/schema.graphql:application/graphql
